name: CI - Test & PHPCS

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests and PHPCS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get proper git diff

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer
          extensions: mbstring, dom, json

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml --testdox

      - name: Get changed PHP files
        id: changed-files
        run: |
          # Get changed files between current branch and target branch
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }}.. -- '*.php' | tr '\n' ' ')
          echo "Changed PHP files: $CHANGED_FILES"
          # Set output for next step
          echo "files=${CHANGED_FILES}" >> $GITHUB_OUTPUT

      - name: Run PHPCS on changed files
        if: steps.changed-files.outputs.files != ''
        run: |
          if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
            echo "Running PHPCS on: ${{ steps.changed-files.outputs.files }}"
            ./vendor/bin/phpcs --standard=phpcs.xml ${{ steps.changed-files.outputs.files }}
          else
            echo "No PHP files changed - skipping PHPCS"
          fi